// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compaction_ledger.sql

package db

import (
	"context"
)

const countLedgerEntries = `-- name: CountLedgerEntries :one
SELECT COUNT(*) FROM compaction_ledger WHERE session_id = ?
`

func (q *Queries) CountLedgerEntries(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countLedgerEntriesStmt, countLedgerEntries, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :execrows
INSERT OR IGNORE INTO compaction_ledger (
    id, session_id, seq, kind, text, relevance, sources, retires, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLedgerEntryParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Seq       int64  `json:"seq"`
	Kind      string `json:"kind"`
	Text      string `json:"text"`
	Relevance int64  `json:"relevance"`
	Sources   string `json:"sources"`
	Retires   string `json:"retires"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (int64, error) {
	result, err := q.exec(ctx, q.createLedgerEntryStmt, createLedgerEntry,
		arg.ID,
		arg.SessionID,
		arg.Seq,
		arg.Kind,
		arg.Text,
		arg.Relevance,
		arg.Sources,
		arg.Retires,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, session_id, seq, kind, text, relevance, sources, retires, created_at FROM compaction_ledger WHERE session_id = ? ORDER BY seq ASC
`

func (q *Queries) ListLedgerEntries(ctx context.Context, sessionID string) ([]CompactionLedger, error) {
	rows, err := q.query(ctx, q.listLedgerEntriesStmt, listLedgerEntries, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompactionLedger{}
	for rows.Next() {
		var i CompactionLedger
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.Text,
			&i.Relevance,
			&i.Sources,
			&i.Retires,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxLedgerSeq = `-- name: MaxLedgerSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) FROM compaction_ledger WHERE session_id = ?
`

func (q *Queries) MaxLedgerSeq(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.maxLedgerSeqStmt, maxLedgerSeq, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
