// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CompactionLedger struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Seq       int64  `json:"seq"`
	Kind      string `json:"kind"`
	Text      string `json:"text"`
	Relevance int64  `json:"relevance"`
	Sources   string `json:"sources"`
	Retires   string `json:"retires"`
	CreatedAt int64  `json:"created_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type McpDisabledServer struct {
	Name string `json:"name"`
}

type McpEnabledServer struct {
	Name string `json:"name"`
}

type Message struct {
	ID                      string          `json:"id"`
	SessionID               string          `json:"session_id"`
	Role                    string          `json:"role"`
	Parts                   string          `json:"parts"`
	Model                   sql.NullString  `json:"model"`
	CreatedAt               int64           `json:"created_at"`
	UpdatedAt               int64           `json:"updated_at"`
	FinishedAt              sql.NullInt64   `json:"finished_at"`
	Provider                sql.NullString  `json:"provider"`
	IsSummaryMessage        int64           `json:"is_summary_message"`
	PrismModelID            sql.NullString  `json:"prism_model_id"`
	PrismModelName          sql.NullString  `json:"prism_model_name"`
	PrismHypercreditSavings sql.NullFloat64 `json:"prism_hypercredit_savings"`
	PrismDollarSavings      sql.NullFloat64 `json:"prism_dollar_savings"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID                  string         `json:"id"`
	ParentSessionID     sql.NullString `json:"parent_session_id"`
	Title               string         `json:"title"`
	MessageCount        int64          `json:"message_count"`
	PromptTokens        int64          `json:"prompt_tokens"`
	CompletionTokens    int64          `json:"completion_tokens"`
	Cost                float64        `json:"cost"`
	UpdatedAt           int64          `json:"updated_at"`
	CreatedAt           int64          `json:"created_at"`
	SummaryMessageID    sql.NullString `json:"summary_message_id"`
	Todos               sql.NullString `json:"todos"`
	Channel             sql.NullString `json:"channel"`
	SummaryCutMessageID sql.NullString `json:"summary_cut_message_id"`
}
